# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'
source 'https://github.com/CocoaPods/Specs.git'
target 'TreeNode' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Masonry'
  pod 'YYCategories'
  # Pods for TreeNode

  target 'TreeNodeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TreeNodeUITests' do
    # Pods for testing
  end

end
